Feature/183 : Customer's name must be replaced with his username overall the site
shermatovsherzod/expro pull request #25
Opened 2022-08-02 07:13 UTC by KhojiakbarFarkhadov

2022-08-02 09:53 UTC, napster1991 requested changes

2022-08-02 09:53 UTC, napster1991 commented on Expro/Areas/Expert/Views/Shared/DocumentPartials/_SingleListItemPartial.cshtml
> +                        <li class="list-inline-item mr-3">@localizer["Author"]: <a href="~/Experts/Details/@Model.Author.ID" class="a-ui"><u>@Model.Author.UserName</u></a></li>
Documentni Authori faqat expert bo'la oladi

2022-08-02 09:53 UTC, napster1991 commented on Expro/Utils/AccountUtil.cs
> +                new Claim(CustomClaimTypes.RatingsInfo, user.Rating.ToString())
nimaga Info digan so'z qo'shildi? shundoligicha turursa ha bo'ladi-ku...

2022-08-02 09:53 UTC, napster1991 commented on Expro/Utils/AccountUtil.cs
> +                new Claim(CustomClaimTypes.PointsInfo, user.Points.ToString())
nimaga Info digan so'z qo'shildi? shundoligicha turursa ha bo'ladi-ku...

2022-08-02 09:53 UTC, napster1991 commented on Expro/ViewModels/AppUserVM.cs
> +            int.TryParse(user.FindFirst(CustomClaimTypes.RatingsInfo).Value, out int ratingsFullInfo);
139-143 qatorlani boshqattan tekshirib chiqin. noto'g'ri qilingan.

2022-08-02 09:53 UTC, napster1991 commented on Expro/ViewModels/Feedback/FeedbackDetailsVM.cs
> +        public string UserName { get; set; }
property nomini xotya bi FeedbackCreatedUserUserName dib qo'yin. bo'masam, bilib bo'mayabti kimni usernameligini.

2022-08-02 09:53 UTC, napster1991 commented on Expro/Views/ServiceOrder/Details.cshtml
> +                    <li class="list-inline-item mr-3">@localizer["Author"]: @Model.Author.UserName</li>
betta ehtiyot bo'lin. chunki ServiceOrderni expert ham create qila oladi

2022-08-02 09:53 UTC, napster1991 commented on Expro/Views/Shared/FinancePanelPartials/_DetailsOfUser.cshtml
> +        <h3 class="mb-0">@Model.User.UserName</h3>
shu faylni bir izlanib ko'rin. qatlada ishlatilinvotkanini aniqlen. skorey vsego, betta FullName qoldirsa ham bo'ladi. lekin birinchi aniq qilin.

2022-08-02 11:26 UTC, KhojiakbarFarkhadov commented on Expro/Views/Shared/FinancePanelPartials/_DetailsOfUser.cshtml
> +        <h3 class="mb-0">@Model.User.UserName</h3>
UserFinancePanelVM ga bog'liq ekan Admin va User area lada ham ishlatilinarkan. Shu sabab bn UserName ga o'zgartirib qo'yudm.

2022-08-02 11:27 UTC, KhojiakbarFarkhadov commented on Expro/Views/ServiceOrder/Details.cshtml
> +                    <li class="list-inline-item mr-3">@localizer["Author"]: @Model.Author.UserName</li>
xo'p. Bu holatda FullName qolgani yaxshimi ?

2022-08-03 17:57 UTC, napster1991 approved these changes

2022-08-04 07:03 UTC, merged